### ISSUE TITLE
[Bug] Incorrect total value returned from authorizeAndFilterReadResponse

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-authz-smart#55] opened 2021-08-20 14:59 UTC
**Describe the bug**
When the authorizeAndFilterReadResponse function runs it does a check to determine whether the user access by the hasAccessToResource function. If they do not it removes it rum the array. The return shows a total of 4 
"type": "searchset", "total": 4,
But in the entry section there are only 3 records.

**Expected behavior**
The total should match the number of entries being returned or potentially have another value that shows it.

**Comment by rsmayda** [comment] 2021-08-23 14:32
Thanks for reporting this. We will be adding this to our backlog!

**Comment by ssvegaraju** [comment] 2021-09-13 17:16
Hey! Just wanted to update on this: a fix for this has just been [merged into mainline](https://github.com/awslabs/fhir-works-on-aws-authz-smart/pull/63)! I'm going to go ahead and close this issue for now, but please feel free to reopen or reach out if the issue is not resolved.

**Closed as completed by ssvegaraju** 2021-09-13 17:16 UTC
Labels: bug
